### ISSUE TITLE
Service in unleash edge helm chart

### ISSUE THREAD

**Issue by yuvals41** [Unleash/helm-charts#106]
### Describe the bug

I deployed the unleash edge helm chart and i set the token and URL correctly and it was really hard to debug because you cant execute shell inside the pod, and when I exposed the unleash-edge pod through ingress, I was getting 503 error and after a while I found out that the service resource wasn't forwarding the traffic correctly to the pod, it was forwarding it on port 80 and it was exposed on the pod in port 3036

I highly recommend to fix this or at least give an option in the values file to change the ports so it will work correctly because I had to pull the helm chart's and change the templates, instead of deploying it remotely without pulling it

Thanks!

### Steps to reproduce the bug

deploy the helm chart and try to reach it from port 80 or 443

### Expected behavior

usually services forward traffic to the pod on port 80 and forward traffic from the pod on the port the pod is exposed at (in this case its 3036)

### Screenshots

![Screenshot from 2023-11-12 21-10-42](https://github.com/Unleash/helm-charts/assets/81389018/7971f946-a71b-4136-8f7c-689773fcd577)

### Unleash version

2.1.0

### Subscription type

Enterprise

### Hosting type

Hosted by Unleash

### SDK information (language and version)

helm

**Comment by nunogois** [comment]
Hi @yuvals41 - Thanks for opening the issue. We'll have a look and get back to you!
