### ISSUE TITLE
Chart.appVersion vs. imageTag 

### ISSUE THREAD

**Issue by lathspell** [Unleash/helm-charts#12]
Currently `_helpers.tpl` defines the label `app.kubernetes.io/version` as `Chart.AppVersion`.
This leads to confusion if `image.tag` is overridden as this is the actual used application version.
`Chart.AppVersion` cannot be overriden when installing a helm chart for reasons I don't know.
Maybe an easy fix would be to set the version label to: `{{ .Values.image.tag | default .Chart.AppVersion }}`?

Of course, another fix would be to timely update this Helm chart after each Unleash release so that most people wouldn't alter `image.tag` but just update to the latest Helm chart version.

**Comment by ivarconr** [comment]
For some reasons the notifications for this ended up in my spam folder. 

> Maybe an easy fix would be to set the version label to: {{ .Values.image.tag | default .Chart.AppVersion }}?

It sounds like a reasonable thing, what do you think @monotek?

> Of course, another fix would be to timely update this Helm chart after each Unleash release so that most people wouldn't alter image.tag but just update to the latest Helm chart version.

I think this is the best option. It would like this process to be more automated, and happen as a result of us pushing a new docker image. We are already automating our docker images with the help of GitHub actions and some custom scripts, maybe we can have those also trigger an action on this repo?

**Comment by monotek** [comment]
No.
Version is the chart version. 
It changes if the chart changes but the image can keep the same.
