### ISSUE TITLE
Docker image version 5.6.7 contains high number of Vulnerabilities wVulnerabilities

### ISSUE THREAD

**Issue by OlegGerber** [Unleash/helm-charts#128]
### Describe the bug

Hello support. 
Please note that unleashorg/unleash-server:5.6.7 contains a high number when many of the issue resolved in 5.7.2 image
see more details at https://github.com/Unleash/unleash/issues/5637 
Any plans to switch to the latest docker image 5.7.xx?

### Subscription type

None

### Hosting type

None

**Comment by sighphyre** [comment]
Hey @OlegGerber, we've updated the charts to the latest version!
