### ISSUE TITLE
Correct Environment Variable in Helm Deployment Template

### ISSUE THREAD

**Issue by linkinn** [Unleash/helm-charts#136]
### Describe the bug

Within the Helm template used to deploy our application, there is an environment variable named DATABASE that is incorrectly configured. It should be DATABASE_NAME.

While investigating an issue with the application not functioning correctly when using a database name other than unleash, we identified the root cause to be the misconfiguration in the Helm deployment template. Within this template, the DATABASE environment variable is set to an incorrect value. This causes issues when the database name is different from unleash, as the application expects an environment variable named DATABASE_NAME.

### Steps to reproduce the bug

1 - Deploy the application using the Helm template.
2 - Change the database name to something other than unleash.
3 - Notice that the application does not function correctly due to expecting an environment variable DATABASE_NAME instead of DATABASE.

### Logs, error output, etc.

```bash
[2024-03-11T19:26:22.801] [ERROR] server-impl.js - Locking error: database "unleash" does not exist
[2024-03-11T19:26:22.803] [ERROR] server-impl.js - Failed to migrate db Error: Connection terminated unexpectedly
    at /unleash/node_modules/pg/lib/client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /unleash/node_modules/unleash-server/dist/lib/util/db-lock.js:30:9
    at async Object.start (/unleash/node_modules/unleash-server/dist/lib/server-impl.js:149:17)
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Connection terminated unexpectedly
    at /unleash/node_modules/pg/lib/client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /unleash/node_modules/unleash-server/dist/lib/util/db-lock.js:30:9
    at async Object.start (/unleash/node_modules/unleash-server/dist/lib/server-impl.js:149:17)
```

### Subscription type

None

### Hosting type

None

**Comment by chriswk** [comment]
Hi @linkinn - You're absolutely correct, and we're sorry. I'll make a PR fixing this. Thank you for taking the time to file this bug.
