### ISSUE TITLE
Unleash edge chart doesn't allow specifying hostAliases

### ISSUE THREAD

**Issue by upcFrost** [Unleash/helm-charts#156]
### Describe the feature request

Hi, apparently the unleash-edge charge doesn't support setting hostAliases, which makes it a bit hard to use when the main unleash server is not on the public DNS. Could you please add a flag for it?

### Solution suggestions

Smth simple like this in the `deployment.yaml` should do
```
      ...
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

**Comment by chriswk** [comment]
Hi @upcFrost - thanks for this issue, I'll add a flag across all three charts
