### ISSUE TITLE
Unable to pass custom authentication using helm chart to unleash

### ISSUE THREAD

**Issue by jensjoy** [Unleash/helm-charts#166]
### Describe the bug

env:
      - name: UNLEASH_DEFAULT_ADMIN_USERNAME
         value: demo
      - name: UNLEASH_DEFAULT_ADMIN_PASSWORD
      value: hello@123
In my helm chart , I have passed the following , even then when I type in kubectl describe pod <pod-name> , i dont see these environment variables being picked up, I only see the database variables being picked up. I am trying to deploy unleash on my AWS eks. 

Whereas , when i try to deploy the same in my local system using docker-compose , these environment variables are being picked up. Any configuration I am missing on ?

### Screenshots

![image](https://github.com/user-attachments/assets/710169e4-67ce-4022-948f-64920f99c285)

### Unleash version

latest

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by chriswk** [comment]
Hi, I just tested this with the newest chart. With the following values file, I get the environment variables as part of the deployment

```yaml
env:
  - name: UNLEASH_DEFAULT_ADMIN_USERNAME
    value: demo
  - name: UNLEASH_DEFAULT_ADMIN_PASSWORD
    value: somepassword
```

I am assuming the indentation in your example was a github formatting error, but I can't reproduce this, the environment variables are added to my deployment.

**Comment by jensjoy** [comment]
This works , thanks for your help :)
