### ISSUE TITLE
Unleash edge chart doesn't support configuring the behaviour

### ISSUE THREAD

**Issue by JorTurFer** [Unleash/helm-charts#175]
### Describe the bug

Recent changes applied on the edge are showing errors during the edge startup informing that future releases won't start if I don't set the behaviour. Currently there isn't any way to configure this and neither a default behaviour set:
https://github.com/Unleash/helm-charts/blob/d3788f53780d87d5ec311aa06b9ed1accbe47177/charts/unleash-edge/templates/deployment.yaml#L39-L57

The error:
```bash
2024-10-25T11:24:54.911113Z ERROR unleash_edge::builder: You should explicitly opt into either strict or dynamic behavior. Edge has defaulted to dynamic to preserve legacy behavior, however we recommend using strict from now on. Not explicitly opting into a behavior will return an error on startup in a future release
```

### Steps to reproduce the bug

Use the latest helm chart

**Comment by chriswk** [comment]
All behaviour is configurable through environment variables. So you can configure it just using normal env declarations
E.g.
```
env:
   - name: STRICT
     value: true
```
But

**Comment by JorTurFer** [comment]
No no, no worries at all! I didn't know that STRICT works to enable the behaviour because I missed that part 🤦 
![image](https://github.com/user-attachments/assets/b8b393df-b683-4643-98fe-1df5119e412b)

Sorry and thanks again for the support! 🙇
