### ISSUE TITLE
No initContainers support

### ISSUE THREAD

**Issue by lbenc135** [Unleash/helm-charts#18]
Hi, I'm having trouble using the chart with a separate postgres database.

We already have a postgres deployment for our other services, and I configured the chart to use it. However, the database "unleash" doesn't exist on that instance (and I don't want to hardcode it there), so migrations fail.

We usually solved this problem by creating an `initContainer` on the service deployment which would create the database before the main container starts. Is there another way to achieve the same thing or could we add support for `initContainers` in the deployment template?

**Comment by ivarconr** [comment]
> We usually solved this problem by creating an initContainer on the service deployment which would create the database before the main container starts. Is there another way to achieve the same thing or could we add support for initContainers in the deployment template?

Having an initContainer to create the database would require it to have permissions to actually create the database. I am not sure if you want that? 

It feels a bit of a stretch to introduce an init container in this chart to support your need to provision the database. How would that be done? Would it just be a configuration where you can attach another container and have it default to nothing? 

Another way of solving this would maybe use an k8s operator [zalando/postgres-operator](https://github.com/zalando/postgres-operator). But that's probably not what you are looking for?

**Comment by ivarconr** [comment]
I personally have no issues introducing support for the user to add their own initContainer, I just have little experience on this personally. 

Would any of you @monotek @chriswk @FredrikOseberg have any opinions on pro/cons?

**Comment by chriswk** [comment]
I think that is reasonable and would increase the use cases for this chart. It would be on the user applying the chart to think of the security considerations.

**Comment by monotek** [comment]
Lets do it.
It's quite common to have configurable init containers in helm charts to be able to customize deployments.

**Comment by ivarconr** [comment]
ok, I am convinced, lets do it @lbenc135 !

**Comment by ivarconr** [comment]
fixed in #21
