### ISSUE TITLE
[Feature Request] Add Unleash Proxy to the chart (As option)

### ISSUE THREAD

**Issue by PhakornKiong** [Unleash/helm-charts#19]
It would be great if `unleash proxy` is included in the helm chart for those wanting to try it in the Kubernetes environment.

**Comment by ivarconr** [comment]
I agree, it would be nice to have this option. The only thing we need to solve for this is a way to provision an Unleash API token for the proxy to be able to connect to Unleash. 

FYI: We have also been thinking that the Unleash-server should have the possibility to have an embedded proxy for low volume traffic, enabled via a config option. This would require us to adapt the proxy a bit to have the option to communicate directly with internal services in Unleash. This is currently not a priority, but an idea. 

Is this something you would be willing to contribute on?

**Comment by themagickoala** [comment]
This is something we'd like to have too - we're using the Gitlab Feature Flags system, so we're not too worried about the API token (per https://gitlab.com/gitlab-org/gitlab/-/issues/273417#note_703026477).

**Comment by mark-jordanovic-lewis** [comment]
I am working on deploying Unleash and the Unleash Proxy into a kubernetes cluster. The manual step of creating an admin API token is undesirable. It would help greatly if either:

- Ephemeral API tokens could be generated for the Proxy, using a proxy-admin user with creds supplied in Helm chart (up to user to encrypt as secrets).
- Implied authorisation of the proxy when it's container is deployed alongside Unleash.
- Admin users can create ephemeral API tokens and can be setup in the Helm chart.

As calls to containers in the same pod happen through loopback it shoudln't be a seurity risk for the second choice.

WDYT?

**Comment by kdawgwilk** [comment]
With these new ENV vars to configure tokens we should be good to go to add the proxy to the helm chart right?

**Comment by devlifealways** [comment]
Indeed it's something we're looking for also, we're playing around with unleash to better understand its integration into our source code, we'll probably hit the EE version soon enough,  I guess the only option we have is to fork the repo and add the proxy into a final chart.
