### ISSUE TITLE
create helm repo for unleash

### ISSUE THREAD

**Issue by monotek** [Unleash/helm-charts#2]
I was not able to find unleash via https://artifacthub.io so it seems there is no helm repo available, which hosts the chart?

Did i just missed it?
Unfortunatly there is no Readme.md provided for the chart too, which contains install instructions.

If there is nor helm repo available jet, you could host the Helm chart via Github releases and Github pages.

I'm experienced with this from other repos (kokuwa, kiwigrid, prometheus-community and so on) so if wanted i coud provide an pr, implementing this via Github actions.

**Comment by monotek** [comment]
I just found: https://github.com/Unleash/helm-charts/pull/1
Seems thats already a copy of my Github workflow :)
Why was this closed?

**Comment by evanstucker-hates-2fa** [comment]
I don't know why https://github.com/Unleash/helm-charts/pull/1 was closed. I am not actively maintaining this repo, so perhaps it was closed because I failed to act on that PR...
