### ISSUE TITLE
Unleash-Proxy helm-chart Deployment template missing quotation mark closing

### ISSUE THREAD

**Issue by fulcrum29** [Unleash/helm-charts#75]
### Describe the bug

There is no quotation closing here, beacause of that UNLEASH_URL is always ended with quota sign, creating 403 error for unleash-proxy.
[https://github.com/Unleash/helm-charts/blob/unleash-proxy-0.3.0/charts/unleash-proxy/templates/deployment.yaml#L57](https://github.com/Unleash/helm-charts/blob/unleash-proxy-0.3.0/charts/unleash-proxy/templates/deployment.yaml#L57)

### Unleash version
unleash-proxy helm chart 0.3.0 

### Subscription type

None

### Hosting type

None

**Comment by alv91** [comment]
fix here https://github.com/Unleash/helm-charts/pull/74

**Comment by daveleek** [comment]
Thank you @fulcrum29 for letting us know, and @alv91 for the PR! We'll have a look!

**Comment by chriswk** [comment]
Fixed with PR #74
