### ISSUE TITLE
helm values for health checks not configurable in unleash-edge

### ISSUE THREAD

**Issue by I3uckwheat** [Unleash/helm-charts#96]
### Describe the feature request

I want to be able to edit the helm values for the livenessProbe and redinessProbe urls. 

### Background

Currently the environment variable for the BASE_PATH will allow overwriting of the base path for unleash-edge. This can cause a situation where your health checks are actually at `/BASE_PATH/internal-backstage/health` and you cannot deploy using the provided helm chart for unleash-edge. In unleash itself, it allows for changing the base path, as well as changing the health-check paths to allow for a base path change. 

### Solution suggestions

1. Update the `deployment.yaml` file to allow for configuration in the `values.yaml` file for the `livenessProbe` and `redinessProbe` values, much like unleash's helm charts
2. Update the `deployment.yaml` file to use the readiness command outlined in the [documentation here](https://docs.getunleash.io/reference/unleash-edge#built-in-ready-check)
   1. This may require an update to the utility that is called to utilize the BASE_PATH environment variable 

PR for the first solution: https://github.com/Unleash/helm-charts/pull/97

**Comment by I3uckwheat** [comment]
This is actively blocking our use of Unleash as we have to use a subroute for this with our current ecosystem and a subdomain is not really an easy option.

**Comment by bcampbellGG** [comment]
We ran into the same issue trying to host unleash-edge with a custom base path, we ended up just forking the chart to modify the .yaml file, this would be a useful addition to have though.
